### ISSUE TITLE
请问有什么办法实现正文非上标引用参考文献呢？

### ISSUE THREAD

**Issue by xirhxq** [BITNP/BIThesis#78]
BIThesis的模板中\cite{}的指令都会将引用放在上标的位置，请问如何实现非上标，即和正文相同位置与大小的引用呢？

**Comment by hushidong** [comment]
https://github.com/hushidong/biblatex-gb7714-2015/issues/86 hzzmail ***@***.*** 签名由 网易邮箱大师 定制 在2021年05月26日 10:23，xirhxq 写道： BIThesis的模板中\cite{}的指令都会将引用放在上标的位置，请问如何实现非上标，即和正文相同位置与大小的引用呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xirhxq** [comment]
完美解决问题！感谢！
